# Generated by Django 5.0.7 on 2024-07-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('data_format', models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx'), ('tsv', 'tsv'), ('json', 'json'), ('xml', 'xml'), ('txt', 'txt'), ('md', 'md'), ('tex', 'tex'), ('jpeg', 'jpeg'), ('png', 'png'), ('zip', 'zip'), ('tar', 'tar'), ('other', 'other')], max_length=20)),
                ('other_data_format', models.CharField(blank=True, max_length=20, null=True)),
                ('degree_of_aggregation', models.CharField(max_length=100)),
            ],
        ),
    ]
